--
-- This file is generated by an embedded javascript directly from UMK
--     Wilko Quak (w.quak@geonovum.nl
delete from BeheerItems;
delete from BeheerItemDependencies;
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD","TPOD standaard","Toepassingsprofiel Omgevingsdocumenten (afgekort TPOD). TPOD is een toepassingsprofiel op STOP: de Standaard Offici&#195;&#171;le Publicaties. TPOD is de specificatie van STOP voor het domein van de Omgevingswet.","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('LVBB-bronhouderskoppelvlak','TPOD');
insert into BeheerItemDependencies(itemid,dependsonitem) values ('DSO-Standaarden','TPOD');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("IMOW","IMOW model","Informatiemodel Omgevingswet","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','IMOW');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("IMOW-XSD","XSD IMOW","XML-Applicatieschema voor gegevensuitwisselling conform de IMOW standaard","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','IMOW-XSD');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-omgevingsplan","TPOD omgevingsplan","Toepassingsprofiel omgevingsplan","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-omgevingsplan');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-waterschapsverordening","TPOD waterschapsverordening","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-waterschapsverordening');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-projectbesluit","TPOD projectbesluit","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-projectbesluit');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-AMvB","TPOD AMvB en MR","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-AMvB');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-UML","TPOD UML","","Geonovum",true,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('IMOW-XSD','TPOD-UML');
insert into BeheerItemDependencies(itemid,dependsonitem) values ('IMOW','TPOD-UML');
insert into BeheerItemDependencies(itemid,dependsonitem) values ('CIMOW','TPOD-UML');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-omgevingsverordening","TPOD Omgevingsverordening","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-omgevingsverordening');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-omgevingsvisie","TPOD Omgevingsvisie","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-omgevingsvisie');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("Presentatie","Presentatiemodel TPOD","","Geonovum",false,"Standaard");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-instructie","TPOD Instructie","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-instructie');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-reactieve-interventie","TPOD reactieve interventie","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-reactieve-interventie');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-voorbereidingsbesluit","TPOD voorbereidingsbesluit","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-voorbereidingsbesluit');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-programma","TPOD programma","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-programma');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("IMOW-waardelijsten","Waardelijsten IMOW","","Geonovum",false,"Standaard");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-Symbolen","Symbolenbibliotheek STOP-TPOD","","Geonovum",false,"Standaard");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-N2000","TPOD Natura 2000-besluit","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-N2000');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("TPOD-kennisgeving","TPOD kennisgeving omgevingsvergunning voor buitenplanse omgevingsplanactiviteiten","","Geonovum",false,"Standaard");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('TPOD','TPOD-kennisgeving');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type) values("CIMOW","CIMOW","Conceptueel Informatiemodel Omgevingswet","Geonovum",false,"Standaard");

