--
-- This file is generated by an embedded javascript directly from UML
--     Wilko Quak (w.quak@geonovum.nl
--
delete from BeheerItems;
delete from BeheerItemDependencies;
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-validatieregels","TPOD validatieregels","Validatie- en conformiteitsregels voor registratie en publicatie van omgevingsdocumenten DSO-LV","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/Validatieregels");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD","TPOD standaard","Toepassingsprofiel Omgevingsdocumenten (afgekort TPOD).","Geonovum",false,"Standaard","https://www.geonovum.nl/geo-standaarden/omgevingswet/STOPTPOD");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/KOOP/LVBB-bronhouderskoppelvlak','ci/Geonovum/TPOD');
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/DSO/DSO-Standaarden','ci/Geonovum/TPOD');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/IMOW","IMOW model","Informatiemodel Omgevingswet","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/CIMOW");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/IMOW');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/IMOW-XSD","XSD IMOW","XML-Applicatieschema voor gegevensuitwisselling conform de IMOW standaard","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/xmlschema");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/IMOW-XSD');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-omgevingsplan","TPOD omgevingsplan","Toepassingsprofiel omgevingsplan","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20Omgevingsplan");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-omgevingsplan');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-waterschapsverordening","TPOD waterschapsverordening","Toepassingsprofiel waterschapsverordening
","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD_Waterschapsverordening");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-waterschapsverordening');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-projectbesluit","TPOD projectbesluit","Toepassingsprofiel projectbesluit
","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20Projectbesluit");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-projectbesluit');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-AMvB","TPOD AMvB en MR","Toepassingsprofiel AMvB/MR","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20AMvB-MR");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-AMvB');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-UML","TPOD UML","UML diagram behorend bij TPOD","Geonovum",true,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/IMOW-XSD','ci/Geonovum/TPOD-UML');
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/IMOW','ci/Geonovum/TPOD-UML');
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/CIMOW','ci/Geonovum/TPOD-UML');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-omgevingsverordening","TPOD omgevingsverordening","Toepassingsprofiel omgevingsverordening","Geonovum",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-omgevingsverordening');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-omgevingsvisie","TPOD omgevingsvisie","","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20Omgevingsvisie");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-omgevingsvisie');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/Presentatie","Presentatiemodel TPOD","","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/Presentatiemodel");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-instructie","TPOD instructie","Toepassingsprofiel instructie.","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20Instructie");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-instructie');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-reactieve-interventie","TPOD reactieve interventie","Toepassingsprofiel reactieve interventie.","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD_Reactieve_interventie");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-reactieve-interventie');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-voorbereidingsbesluit","TPOD voorbereidingsbesluit","Toepassingsprofiel voorbereidingsbesluit.","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD_Voorbereidingsbesluit");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-voorbereidingsbesluit');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-programma","TPOD programma","Toepassingsprofiel programma","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20Programma");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-programma');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/IMOW-waardelijsten","Waardelijsten IMOW","Waardelijsten IMOW zoals gepubliceerd in de stelselcatalogus","Geonovum",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/IMOW-waardelijsten');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-Symbolen","Symbolenbibliotheek STOP-TPOD","Symbolen","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/Presentatiemodel");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/IMOW-waardelijsten','ci/Geonovum/TPOD-Symbolen');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-N2000","TPOD Natura 2000-besluit","Toepassingsprofiel Natura 2000-besluiten","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20Natura%202000-besluiten");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-N2000');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/TPOD-kennisgeving","TPOD kennisgeving omgevingsvergunning voor buitenplanse omgevingsplanactiviteiten","Toepassingsprofiel kennisgeving omgevingsvergunning voor
buitenplanse omgevingsplanactiviteit.","Geonovum",false,"Standaard","https://github.com/Geonovum/TPOD/tree/master/TPOD%20Kennisgeving%20omgevingsvergunning%20buitenplanse%20omgevingsplanactiviteit");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/Geonovum/TPOD-kennisgeving');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/Geonovum/CIMOW","CIMOW","Conceptueel Informatiemodel Omgevingswet","Geonovum",false,"Standaard","");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/KOOP/LVBB-bronhouderskoppelvlak","LVBB bronhouderskoppelvlak","","KOOP",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/DSO/DSO-Standaarden','ci/KOOP/LVBB-bronhouderskoppelvlak');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/KOOP/STOP","STOP standaard","","KOOP",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/Geonovum/TPOD','ci/KOOP/STOP');
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/DSO/DSO-Standaarden','ci/KOOP/STOP');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/IMAM","IMAM","","RWS",false,"Standaard","");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/IMTR","IMTR","","RWS",false,"Standaard","");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/STAM","STAM","De Standaard aanvragen en meldingen (STAM) en het bijbehorende informatiemodel (IMAM) helpen bij het afleveren van een vergunningaanvraag of melding bij overheden.","RWS",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/RWS/STTR-XSD','ci/RWS/STAM');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/STTR","STTR","","RWS",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/RWS/IMTR-XSD','ci/RWS/STTR');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/STAM-Voorbeelden","Voorbeeldbestanden-STAM","","RWS",false,"Standaard","");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/STTR-Voorbeelden","Voorbeeldbestanden-STTR","","RWS",false,"Standaard","");
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/IMTR-XSD","XSD-IMTR","","RWS",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/RWS/STTR-Voorbeelden','ci/RWS/IMTR-XSD');
insert into BeheerItems(id,naam,omschrijving,organisatie,intern,type,releaselocatie) values("ci/RWS/STTR-XSD","XSD-STAM","","RWS",false,"Standaard","");
insert into BeheerItemDependencies(itemid,dependsonitem) values ('ci/RWS/STAM-Voorbeelden','ci/RWS/STTR-XSD');
